# Generated by Django 6.0.6 on 2026-06-28 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('technical', 'Tech Team'), ('marketing', 'Marketing Team'), ('accommodation', 'Accommodation Partner')], max_length=30)),
                ('profile_photo', models.ImageField(upload_to='crew_photos/')),
                ('whatsapp', models.CharField(max_length=15)),
                ('skills', models.TextField()),
                ('experience', models.TextField(blank=True)),
                ('why_join', models.TextField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('tech_stack', models.CharField(blank=True, max_length=300)),
                ('social_media_handles', models.CharField(blank=True, max_length=300)),
                ('campaign_idea', models.TextField(blank=True)),
                ('city_area', models.CharField(blank=True, max_length=100)),
                ('accommodation_type', models.CharField(blank=True, max_length=200)),
                ('crew_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('referral_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('referral_count', models.PositiveIntegerField(default=0)),
                ('reward_points', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crew_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('college_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1)),
                ('city', models.CharField(max_length=100)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('why_join', models.TextField(help_text='CampusCrew kyun join karna chahte ho?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
