# Generated by Django 5.2.15 on 2026-06-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='why_join',
            field=models.TextField(help_text='Why do you want to join CampusCrew?'),
        ),
    ]
